export const DAYS_TO_STALE_DATA = 2
export const MINUTES_TO_FAILED_SCRAPE = 1

export enum UserSyncStorageKeys {
    LAST_SCRAPE_INITIATED_AT = 'LAST_SCRAPE_INITIATED_AT',
    LAST_SCRAPE_HEARTBEAT_AT = 'LAST_SCRAPE_HEARTBEAT_AT',
    LAST_SCRAPE_STATUS = 'LAST_SCRAPE_STATUS',
    LAST_SUCCESSFUL_SCRAPE_AT = 'LAST_SUCCESSFUL_SCRAPE_AT'
}

export enum ScrapeStatus {
    PENDING = 'pending',
    COMPLETED = 'completed',
    FAILED = 'failed',
}
