name: GitHub Actions Demo
run-name: ${{ github.actor }} deployed 🚀
on:
  push:
    branches:
      - main
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: "yarn"
      - run: yarn install
      - run: yarn build
      - run: yarn deploy
