name: GitHub Actions Demo
run-name: ${{ github.actor }} deployed 🚀
on:
  push:
    branches:
      - main
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      # - name: Use Node.js 18
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: "18"
      #     cache: "yarn"
      #     cache-dependency-path: frontend/package.json
      - run: yarn install
        working-directory: ./frontend
      - run: yarn build
        working-directory: ./frontend
      - run: yarn deploy
        working-directory: ./frontend
