name: GitHub Actions Demo
run-name: ${{ github.actor }} deployed 🚀
on:
  push:
    branches:
      - main
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: cd frontend
      - run: yarn build
      - run: yarn deploy
