name: GitHub Actions Demo
run-name: ${{ github.actor }} deployed 🚀
on:
  push:
    branches:
      - main
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build # will run `yarn build` command
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: deploy # will run `yarn test` command
